# Run this from the project root using: 'rake -f test/Rakefile'
# Or from within the 'test' directory using: 'rake'

require "rake/testtask"

pattern = Dir.getwd == __dir__ ? "test*.rb" : "test/test*.rb"

Rake::TestTask.new do |t|
  t.test_files = FileList[pattern]
  t.verbose = true
end

task default: :test