require 'rake/clean'

targetfile = "tfe"
srcfiles = FileList["tfe.c", "tfetextview.c", "resources.c"]
uifile = "tfe.ui"
rscfile = srcfiles[2]
objfiles = srcfiles.ext(".o")
gresource_xml = "tfe.gresource.xml"

CLEAN.include(targetfile, objfiles, rscfile)

task default: targetfile

file targetfile => objfiles do |t|
  sh "gcc -o #{t.name} #{t.prerequisites.join(' ')} `pkg-config --libs gtk4`"
end

objfiles.each do |obj|
  src = obj.ext(".c")
  file obj => src do |t|
    sh "gcc -c -o #{t.name} `pkg-config --cflags gtk4` #{t.source}"
  end
end

file rscfile => uifile do |t|
  sh "glib-compile-resources #{gresource_xml} --target=#{t.name} --generate-source"
end
